project:
  type: website
  output-dir: docs

website:
  title: "dprtask"
  navbar:
    left:
      - href: index.qmd
        text: Task

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



